# Use a Golang base image
FROM golang:1.22.0-alpine AS builder

# Set the current working directory inside the container
WORKDIR /app

# Copy the Go modules files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the source code into the container
COPY . .

# Build the Go app
RUN CGO_ENABLED=0 GOOS=linux go build -o app .

# Use a minimal alpine image as the base image for the final image
FROM alpine:latest

# Copy the executable from the builder stage into the final image
COPY --from=builder /app/app /app/app

# Expose the port on which your Go application will listen
EXPOSE 3001

# Command to run the Go application
CMD ["/app/app"]
